name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.0.0]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install yarn
      run: npm install -g yarn 

    - name: Install dependencies
      run: yarn install
    
    - name: Run the project
      run: yarn serve:ssl
